module.exports = [
  {
    venue: { layout: { rows: 10, columns: 50 } },
    seats: {
      a1: { id: 'a1', row: 'a', column: 1, status: 'AVAILABLE' },
      b5: { id: 'b5', row: 'b', column: 5, status: 'AVAILABLE' },
      h7: { id: 'h7', row: 'h', column: 7, status: 'AVAILABLE' },
    },
  },
  {
    venue: { layout: { rows: 8, columns: 10 } },
    seats: {
      a3: { id: 'a3', row: 'a', column: 3, status: 'AVAILABLE' },
      a9: { id: 'a9', row: 'a', column: 9, status: 'AVAILABLE' },
      a10: { id: 'a10', row: 'a', column: 10, status: 'AVAILABLE' },
      b3: { id: 'b3', row: 'b', column: 3, status: 'AVAILABLE' },
      b5: { id: 'b5', row: 'b', column: 5, status: 'AVAILABLE' },
      b6: { id: 'b6', row: 'b', column: 6, status: 'AVAILABLE' },
      b7: { id: 'b7', row: 'b', column: 7, status: 'AVAILABLE' },
      c5: { id: 'c5', row: 'c', column: 5, status: 'AVAILABLE' },
      c6: { id: 'c6', row: 'c', column: 6, status: 'AVAILABLE' },
      c7: { id: 'c7', row: 'c', column: 7, status: 'AVAILABLE' },
      f5: { id: 'f5', row: 'f', column: 5, status: 'AVAILABLE' },
      f6: { id: 'f6', row: 'f', column: 6, status: 'AVAILABLE' },
      f10: { id: 'f10', row: 'f', column: 10, status: 'AVAILABLE' },
    },
  },
  {
    venue: { layout: { rows: 10, columns: 12 } },
    seats: {
      a1: { id: 'a1', row: 'a', column: 1, status: 'AVAILABLE' },
      a2: { id: 'a2', row: 'a', column: 2, status: 'AVAILABLE' },
      a3: { id: 'a3', row: 'a', column: 3, status: 'AVAILABLE' },
      a4: { id: 'a4', row: 'a', column: 4, status: 'AVAILABLE' },
      a5: { id: 'a5', row: 'a', column: 5, status: 'AVAILABLE' },
      a6: { id: 'a6', row: 'a', column: 6, status: 'AVAILABLE' },
      a7: { id: 'a7', row: 'a', column: 7, status: 'AVAILABLE' },
      a8: { id: 'a8', row: 'a', column: 8, status: 'AVAILABLE' },
      a9: { id: 'a9', row: 'a', column: 9, status: 'AVAILABLE' },
      a10: { id: 'a10', row: 'a', column: 10, status: 'AVAILABLE' },
      a11: { id: 'a11', row: 'a', column: 11, status: 'AVAILABLE' },
      a12: { id: 'a12', row: 'a', column: 12, status: 'AVAILABLE' },

      b1: { id: 'b1', row: 'b', column: 1, status: 'AVAILABLE' },
      b2: { id: 'b2', row: 'b', column: 2, status: 'AVAILABLE' },
      b3: { id: 'b3', row: 'b', column: 3, status: 'AVAILABLE' },
      b4: { id: 'b4', row: 'b', column: 4, status: 'AVAILABLE' },
      b5: { id: 'b5', row: 'b', column: 5, status: 'AVAILABLE' },
      b6: { id: 'b6', row: 'b', column: 6, status: 'AVAILABLE' },
      b7: { id: 'b7', row: 'b', column: 7, status: 'AVAILABLE' },
      b8: { id: 'b8', row: 'b', column: 8, status: 'AVAILABLE' },
      b9: { id: 'b9', row: 'b', column: 9, status: 'AVAILABLE' },
      b10: { id: 'b10', row: 'b', column: 10, status: 'AVAILABLE' },
      b11: { id: 'b11', row: 'b', column: 11, status: 'AVAILABLE' },
      b12: { id: 'b12', row: 'b', column: 12, status: 'AVAILABLE' },

      c1: { id: 'c1', row: 'c', column: 1, status: 'AVAILABLE' },
      c2: { id: 'c2', row: 'c', column: 2, status: 'AVAILABLE' },
      c3: { id: 'c3', row: 'c', column: 3, status: 'AVAILABLE' },
      c4: { id: 'c4', row: 'c', column: 4, status: 'AVAILABLE' },
      c5: { id: 'c5', row: 'c', column: 5, status: 'AVAILABLE' },
      c6: { id: 'c6', row: 'c', column: 6, status: 'AVAILABLE' },
      c7: { id: 'c7', row: 'c', column: 7, status: 'AVAILABLE' },
      c8: { id: 'c8', row: 'c', column: 8, status: 'AVAILABLE' },
      c9: { id: 'c9', row: 'c', column: 9, status: 'AVAILABLE' },
      c10: { id: 'c10', row: 'c', column: 10, status: 'AVAILABLE' },
      c11: { id: 'c11', row: 'c', column: 11, status: 'AVAILABLE' },
      c12: { id: 'c12', row: 'c', column: 12, status: 'AVAILABLE' },

      d1: { id: 'd1', row: 'd', column: 1, status: 'AVAILABLE' },
      d2: { id: 'd2', row: 'd', column: 2, status: 'AVAILABLE' },
      d3: { id: 'd3', row: 'd', column: 3, status: 'AVAILABLE' },
      d4: { id: 'd4', row: 'd', column: 4, status: 'AVAILABLE' },
      d5: { id: 'd5', row: 'd', column: 5, status: 'AVAILABLE' },
      d6: { id: 'd6', row: 'd', column: 6, status: 'AVAILABLE' },
      d7: { id: 'd7', row: 'd', column: 7, status: 'AVAILABLE' },
      d8: { id: 'd8', row: 'd', column: 8, status: 'AVAILABLE' },
      d9: { id: 'd9', row: 'd', column: 9, status: 'AVAILABLE' },
      d10: { id: 'd10', row: 'd', column: 10, status: 'AVAILABLE' },
      d11: { id: 'd11', row: 'd', column: 11, status: 'AVAILABLE' },
      d12: { id: 'd12', row: 'd', column: 12, status: 'AVAILABLE' },

      e1: { id: 'e1', row: 'e', column: 1, status: 'AVAILABLE' },
      e2: { id: 'e2', row: 'e', column: 2, status: 'AVAILABLE' },
      e3: { id: 'e3', row: 'e', column: 3, status: 'AVAILABLE' },
      e4: { id: 'e4', row: 'e', column: 4, status: 'AVAILABLE' },
      e5: { id: 'e5', row: 'e', column: 5, status: 'AVAILABLE' },
      e6: { id: 'e6', row: 'e', column: 6, status: 'AVAILABLE' },
      e7: { id: 'e7', row: 'e', column: 7, status: 'AVAILABLE' },
      e8: { id: 'e8', row: 'e', column: 8, status: 'AVAILABLE' },
      e9: { id: 'e9', row: 'e', column: 9, status: 'AVAILABLE' },
      e10: { id: 'e10', row: 'e', column: 10, status: 'AVAILABLE' },
      e11: { id: 'e11', row: 'e', column: 11, status: 'AVAILABLE' },
      e12: { id: 'e12', row: 'e', column: 12, status: 'AVAILABLE' },

      f1: { id: 'f1', row: 'f', column: 1, status: 'AVAILABLE' },
      f2: { id: 'f2', row: 'f', column: 2, status: 'AVAILABLE' },
      f3: { id: 'f3', row: 'f', column: 3, status: 'AVAILABLE' },
      f4: { id: 'f4', row: 'f', column: 4, status: 'AVAILABLE' },
      f5: { id: 'f5', row: 'f', column: 5, status: 'AVAILABLE' },
      f6: { id: 'f6', row: 'f', column: 6, status: 'AVAILABLE' },
      f7: { id: 'f7', row: 'f', column: 7, status: 'AVAILABLE' },
      f8: { id: 'f8', row: 'f', column: 8, status: 'AVAILABLE' },
      f9: { id: 'f9', row: 'f', column: 9, status: 'AVAILABLE' },
      f10: { id: 'f10', row: 'f', column: 10, status: 'AVAILABLE' },
      f11: { id: 'f11', row: 'f', column: 11, status: 'AVAILABLE' },
      f12: { id: 'f12', row: 'f', column: 12, status: 'AVAILABLE' },

      g1: { id: 'g1', row: 'g', column: 1, status: 'AVAILABLE' },
      g2: { id: 'g2', row: 'g', column: 2, status: 'AVAILABLE' },
      g3: { id: 'g3', row: 'g', column: 3, status: 'AVAILABLE' },
      g4: { id: 'g4', row: 'g', column: 4, status: 'AVAILABLE' },
      g5: { id: 'g5', row: 'g', column: 5, status: 'AVAILABLE' },
      g6: { id: 'g6', row: 'g', column: 6, status: 'AVAILABLE' },
      g7: { id: 'g7', row: 'g', column: 7, status: 'AVAILABLE' },
      g8: { id: 'g8', row: 'g', column: 8, status: 'AVAILABLE' },
      g9: { id: 'g9', row: 'g', column: 9, status: 'AVAILABLE' },
      g10: { id: 'g10', row: 'g', column: 10, status: 'AVAILABLE' },
      g11: { id: 'g11', row: 'g', column: 11, status: 'AVAILABLE' },
      g12: { id: 'g12', row: 'g', column: 12, status: 'AVAILABLE' },

      h1: { id: 'h1', row: 'h', column: 1, status: 'AVAILABLE' },
      h2: { id: 'h2', row: 'h', column: 2, status: 'AVAILABLE' },
      h3: { id: 'h3', row: 'h', column: 3, status: 'AVAILABLE' },
      h4: { id: 'h4', row: 'h', column: 4, status: 'AVAILABLE' },
      h5: { id: 'h5', row: 'h', column: 5, status: 'AVAILABLE' },
      h6: { id: 'h6', row: 'h', column: 6, status: 'AVAILABLE' },
      h7: { id: 'h7', row: 'h', column: 7, status: 'AVAILABLE' },
      h8: { id: 'h8', row: 'h', column: 8, status: 'AVAILABLE' },
      h9: { id: 'h9', row: 'h', column: 9, status: 'AVAILABLE' },
      h10: { id: 'h10', row: 'h', column: 10, status: 'AVAILABLE' },
      h11: { id: 'h11', row: 'h', column: 11, status: 'AVAILABLE' },
      h12: { id: 'h12', row: 'h', column: 12, status: 'AVAILABLE' },

      i1: { id: 'i1', row: 'i', column: 1, status: 'AVAILABLE' },
      i2: { id: 'i2', row: 'i', column: 2, status: 'AVAILABLE' },
      i3: { id: 'i3', row: 'i', column: 3, status: 'AVAILABLE' },
      i4: { id: 'i4', row: 'i', column: 4, status: 'AVAILABLE' },
      i5: { id: 'i5', row: 'i', column: 5, status: 'AVAILABLE' },
      i6: { id: 'i6', row: 'i', column: 6, status: 'AVAILABLE' },
      i7: { id: 'i7', row: 'i', column: 7, status: 'AVAILABLE' },
      i8: { id: 'i8', row: 'i', column: 8, status: 'AVAILABLE' },
      i9: { id: 'i9', row: 'i', column: 9, status: 'AVAILABLE' },
      i10: { id: 'i10', row: 'i', column: 10, status: 'AVAILABLE' },
      i11: { id: 'i11', row: 'i', column: 11, status: 'AVAILABLE' },
      i12: { id: 'i12', row: 'i', column: 12, status: 'AVAILABLE' },

      j1: { id: 'j1', row: 'j', column: 1, status: 'AVAILABLE' },
      j2: { id: 'j2', row: 'j', column: 2, status: 'AVAILABLE' },
      j3: { id: 'j3', row: 'j', column: 3, status: 'AVAILABLE' },
      j4: { id: 'j4', row: 'j', column: 4, status: 'AVAILABLE' },
      j5: { id: 'j5', row: 'j', column: 5, status: 'AVAILABLE' },
      j6: { id: 'j6', row: 'j', column: 6, status: 'AVAILABLE' },
      j7: { id: 'j7', row: 'j', column: 7, status: 'AVAILABLE' },
      j8: { id: 'j8', row: 'j', column: 8, status: 'AVAILABLE' },
      j9: { id: 'j9', row: 'j', column: 9, status: 'AVAILABLE' },
      j10: { id: 'j10', row: 'j', column: 10, status: 'AVAILABLE' },
      j11: { id: 'j11', row: 'j', column: 11, status: 'AVAILABLE' },
      j12: { id: 'j12', row: 'j', column: 12, status: 'AVAILABLE' },
    },
  },
];
